name: Type Check

on:
  workflow_call:

jobs:
  type-check:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v7.0.0

    - uses: actions/setup-node@v6.4.0
      with:
        node-version: 24.16.0

    - name: Restore Build Cache
      id: restore-build-cache
      uses: actions/cache/restore@v5.0.5
      with:
        path: |
          common/temp
          projects/*/.rush/temp
          projects/*/node_modules
          ~/.cache/Cypress
          projects/*/dist
          projects/client/lib
          projects/components/lib
        key: ${{ runner.os }}-build-${{ hashFiles('common/config/rush/repo-state.json', 'common/config/rush/pnpm-config.json', 'rush.json', '.github/workflows/ci-salt.txt') }}
        fail-on-cache-miss: true

    - name: Configure Discord Secrets
      run: (cd projects/discord && ./client_config_ci.sh)
      env:
        # Any values will do, discord application does not run during this job
        DISCORD_CLIENT_ID: fake_discord_client_id
        DISCORD_CLIENT_SECRET: fake_discord_client_secret
        DISCORD_GUILD_ID: fake_guild_id
        DISCORD_SESSION_SECRET: fake_discord_session_secret
        DISCORD_REDIRECT_URI: fake_discord_redirect_uri

    - name: Type Check
      run: node common/scripts/install-run-rush.js type-check --verbose
